// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearCommander.png
var resourceKrankyBearCommanderPngData []byte
var resourceKrankyBearCommanderPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearCommander.png",
	StaticContent: resourceKrankyBearCommanderPngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}
