[Details]
ID = "com.github.amarillier.KrankyBearCommander"
Name = "KrankyBear Commander"
Creator = "Allan Marillier"
  Version = "0.2.0"
Build = 2
Icon = "KrankyBearCommander.png"

[Migrations]
  fyneDo = true

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"